spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KC_EXTERNAL_URL}
        registration:
          keycloak:
            redirect-uri: http://localhost:8080/UA/sso/login
